### ISSUE TITLE
pages load indefinitely 

### ISSUE THREAD

**Issue by jackhftang** [johnpolacek/controldeck.js#7]
This is what I did

> git clone git://github.com/dfcb/controldeck.js.git
> npm install 
> sudo node app
> But unfortunately, go to http://localhost:8080/ load forever. 
> curl http://localhost:8080/ confirm that it run for a long time and get empty respond. 
> I tried to chmod a+rw . -R, but still in vein.

Any idea? Thanks

**Comment by jackhftang** [comment]
more details,
I can see "pathname: ..." from stdout.
but no paths give a reply, including /favicon.ico, index.html, notes.txt...

**Comment by jackhftang** [comment]
update:
I tried again on a ubuntu server and it works smoothly.
But still not work on my Arch pc. I though there may be some libraries missing.
Any ideas?

**Comment by secunit64** [comment]
Same errors here ... What node version are you using jackhftang ?

**Comment by jackhftang** [comment]
I tried v0.10.5 and v0.10.7, both give the same result.

**Comment by jackhftang** [comment]
Oh, I use nvm to use v0.8.23 and now it run with no problems.
